name: Check for errors, clippy, format, test and build

on: [push, pull_request, workflow_dispatch, workflow_call]

env:
  CARGO_TERM_COLOR: always

jobs:
  check-test-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
          os: [macos-latest, ubuntu-latest, windows-latest, ubuntu-24.04-arm]

    steps:
      - uses: actions/checkout@v4
      - uses: swatinem/rust-cache@v2

      - name: Check for errors
        run: cargo check --all-targets --verbose
      
      - name: Run tests
        run: cargo test --verbose

      - name: Check code formatting
        run: cargo fmt --all --check --verbose

      - name: Check code with clippy
        run: cargo clippy --all-targets --verbose

      - name: Build in release mode
        run: cargo build --release --verbose

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: fit2gpx_${{ runner.os }}_${{ runner.arch }}
          path: |
              target/release/fit2gpx
              target/release/fit2gpx.exe
